import { IQuestion } from "../Iquestion";

export class ExamData {

    public questions: IQuestion[] = [
        {
            no: "1",
            isAnswer: true,
            answer: "A",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "2",
            isAnswer: true,
            answer: "B",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "3",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "4",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: true,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "5",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "6",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "7",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "8",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "9",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "10",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "11",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "12",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "13",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "14",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "15",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "16",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "17",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "18",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "19",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "20",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "21",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "22",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "23",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "24",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "25",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "26",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "27",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "28",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "29",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "30",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "31",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "32",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "33",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "34",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "35",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "36",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "37",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "38",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "39",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "40",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "41",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "42",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "43",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "44",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "45",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        },
        {
            no: "46",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Có bao nhiêu cách chọn hai học sinh từ một nhóm gồm học sinh ?",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer1A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer1B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer1C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer1D.png"
            
        },
        {
            no: "47",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian mặt phẳng (P):x +2y +3z -5 = 0 có một vectơ pháp tuyến là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer2A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer2B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer2C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer2D.png"
        },
        {
            no: "48",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Trong không gian cho hai điểm A(2; -4; 3) và B(2; 2; 7). Trung điểm của đoạn thẳng có tọa độ là",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer3A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer3B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer3C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer3D.png"
        },
        {
            no: "49",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "",
            answerA: "http://localhost:4200/assets/image/questionAnswer4A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer4B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer4C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer4D.png"
        },
        {
            no: "50",
            isAnswer: false,
            answer: "",
            correctAnswer: "B",
            difficultyLevel: 0,
            isFlag: false,
            question: "Cho hình chóp S.ABCD có đáy là hình vuông cạnh a, SA vuông góc với mặt phẳng đáy và SB = 2. Góc giữa đường thẳng và mặt phẳng đáy bằng",
            questionImg: "http://localhost:4200/assets/image/questionImg5.png",
            answerA: "http://localhost:4200/assets/image/questionAnswer5A.png",
            answerB: "http://localhost:4200/assets/image/questionAnswer5B.png",
            answerC: "http://localhost:4200/assets/image/questionAnswer5C.png",
            answerD: "http://localhost:4200/assets/image/questionAnswer5D.png"
        }
    ];

    randomAnswer(){
        const answers = "ABCD";

        return answers.charAt(Math.floor(Math.random() * answers.length));
    }
}
